Modify CentOSDepsUnattended script to install a version of openssl that is supported by node
This change fixes a runtime issue with the licode DTLS/SSL handshake.  It was previously having
an error during the handshake process:

ERROR: dtls.DtlsSocket - SSL error 1

It turns out that using the system openssl isn't recommended.  The script has been modified to
query node js via `node -pe process.versions.openssl` to determine which version of openssl to use.

Note that the system openssl is a newer version than the one node is expecting:

$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017

$ node -pe process.versions.openssl
1.0.1l